services:
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: react_vite_app
    env_file:
      - ./frontend-react/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    container_name: nestjs_app
    env_file:
      - ./backend-nest/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend-nest:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=7vGWe4kq8o3xBo
      - DB_NAME=helpdesk

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7vGWe4kq8o3xBo
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: